# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 18.x]

    steps:
    - uses: actions/checkout@v2

    - name: setup prerequisites (linux)
      run: |
        sudo apt update 
        sudo apt install pkg-config libudev-dev libusb-1.0-0-dev
  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm run prepublishOnly
    - run: npm install --build-from-source
#    - run: npm ci
#    - run: npm run build --if-present
    - run: npm test
